### ISSUE TITLE
Internal Server Error в SmartAppBrainRecognizer

### ISSUE THREAD

**Issue by snyuryev** [sberdevices/salutejs#161]
В логах вижу такую ошибку

```
Error: Internal Server Error
    at new FetchError (/workspace/node_modules/@salutejs/recognizer-smartapp-brain/dist/lib/index.js:71:28)
    at SmartAppBrainRecognizer.<anonymous> (/workspace/node_modules/@salutejs/recognizer-smartapp-brain/dist/lib/index.js:134:37)
    at step (/workspace/node_modules/@salutejs/recognizer-smartapp-brain/dist/lib/index.js:57:23)
```

**Comment by awinogradov** [comment]
Проблема на стороне SmartApp Brain. Будет решено не здесь
