### ISSUE TITLE
TypeError: Cannot read property 'device' of undefined

### ISSUE THREAD

**Issue by snyuryev** [sberdevices/salutejs#162]
Иногда (редко) проскакивает подобная ошибка.
```
TypeError: Cannot read property 'device' of undefined
    at Object.createSaluteResponse (/workspace/node_modules/@salutejs/scenario/dist/lib/createSaluteResponse.js:23:29)
    at Object.exports.sberFulfillment (/workspace/lib/meditation/index.js:72:28)
```

**Comment by snyuryev** [comment]
@sasha-tlt пустой body приходит

**Comment by sasha-tlt** [comment]
Может такое быть, что это не наш vps, а какой-то другой сервис?

**Comment by snyuryev** [comment]
@sasha-tlt не думаю, адрес вебхука нигде больше не указывался
